name: GoReleaser Check

on:
  push:
    paths:
      - '.goreleaser.yaml'
  pull_request:
    paths:
      - '.goreleaser.yaml'

# Permissions are granted per-job when write access is needed
permissions: read-all

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
        with:
          install-only: true

      - name: Run GoReleaser Check
        run: goreleaser check
